function initpos = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  INITPOSFOR = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  INITPOSFOR = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  INITPOSFOR = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  initposfor = importfile("C:\Users\nhnha\OneDrive\Desktop\Whisker paper\Living-machine2023\init_pos_for.xlsx", "Sheet1", [2, 7]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Mar-2023 11:03:54

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    dataLines = [3, 7];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Pressure", "InitX", "InitZ", "offset"];
opts.SelectedVariableNames = ["Pressure", "InitX", "InitZ", "offset"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
initpos = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    initpos = [initpos; tb]; %#ok<AGROW>
end

%% Convert to output type
initpos = table2array(initpos);
end